theme: jekyll-theme-midnight
title: Welcome to Arrioc’s ePortfolio!
description: I’m Jessica Kilbourne, and this is an ePortfolio I started in my CS-499 Capstone Course (T5477).
image: https://github.com/Arrioc/arrioc.github.oi/issues/2#issue-912579440
