theme: jekyll-theme-midnight
title: Welcome to Arrioc’s Homepage!
description: I’m Jessica Kilbourne, and this is an ePortfolio I started in my CS-499 Capstone Course (T5477).
image: ![myCatASCII](https://user-images.githubusercontent.com/73560858/120911070-355f7b80-c652-11eb-96c7-309bdd3cd158.png)
